// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Flowbit.Qullqa.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace Flowbit.Qullqa.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705041315_Delivery_Initial")]
    partial class Delivery_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.Aggregates.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<string>("CurrentLabel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("current_label");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("destination");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("driver_name");

                    b.Property<string>("DriverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("driver_phone");

                    b.Property<DateTimeOffset>("EstimatedArrival")
                        .HasColumnType("datetime")
                        .HasColumnName("estimated_arrival");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("origin");

                    b.Property<int?>("PurchaseDetailId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_detail_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("TotalWeightUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("total_weight_unit");

                    b.Property<decimal>("TotalWeightValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_weight_value");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tracking_number");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vehicle");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_deliveries_business_id");

                    b.HasIndex("PurchaseDetailId")
                        .HasDatabaseName("ix_deliveries_purchase_detail_id");

                    b.ToTable("deliveries");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.Entities.Waypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("district");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("label");

                    b.Property<bool>("Reached")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("reached");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int")
                        .HasColumnName("sequence_order");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_waypoints");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_waypoints_delivery_id");

                    b.ToTable("waypoints");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ruc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_businesses");

                    b.ToTable("businesses");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_users_business_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Iam.Domain.Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Position = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Position = "CASHIER"
                        },
                        new
                        {
                            Id = 3,
                            Position = "WAREHOUSE"
                        });
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_price");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_products_business_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_warehouses_business_id");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("date")
                        .HasColumnName("expiration");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("purchase_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_batches");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_batches_business_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_batches_product_id");

                    b.ToTable("batches");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int")
                        .HasColumnName("minimum_stock");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("StockUnit")
                        .HasColumnType("int")
                        .HasColumnName("stock_unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_inventory_items_business_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_items_warehouse_id");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_items_product_id_warehouse_id");

                    b.ToTable("inventory_items");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("registered_at");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("supplier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_stock_movements_business_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stock_movements_product_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_stock_movements_warehouse_id");

                    b.ToTable("stock_movements");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Sales.Domain.Model.Aggregates.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("registered_at");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_customers_business_id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_sales_business_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_customer_id");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Sales.Domain.Model.Entities.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("discount");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sale_details");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_details_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_details_sale_id");

                    b.ToTable("sale_details");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Aggregates.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_date");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_purchase_orders_business_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Aggregates.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ruc");

                    b.Property<DateTime>("Since")
                        .HasColumnType("date")
                        .HasColumnName("since");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_suppliers_business_id");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Entities.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("DeliveryTrackingNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("delivery_tracking_num");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("discount");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_details");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_order_details_product_id");

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("ix_purchase_order_details_purchase_id");

                    b.ToTable("purchase_order_details");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.Aggregates.Delivery", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_business_business_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Entities.PurchaseOrderDetail", null)
                        .WithMany()
                        .HasForeignKey("PurchaseDetailId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deliveries_purchase_order_detail_purchase_detail_id");

                    b.OwnsOne("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.ValueObjects.GeoCoordinate", "CurrentLocation", b1 =>
                        {
                            b1.Property<int>("DeliveryId")
                                .HasColumnType("int")
                                .HasColumnName("delivery_id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("longitude");

                            b1.HasKey("DeliveryId")
                                .HasName("pk_delivery_current_locations");

                            b1.ToTable("delivery_current_locations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_delivery_current_locations_deliveries_delivery_id");
                        });

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.Entities.Waypoint", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.Aggregates.Delivery", null)
                        .WithMany("Waypoints")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_waypoints_deliveries_delivery_id");

                    b.OwnsOne("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.ValueObjects.GeoCoordinate", "Location", b1 =>
                        {
                            b1.Property<int>("WaypointId")
                                .HasColumnType("int")
                                .HasColumnName("waypoint_id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("longitude");

                            b1.HasKey("WaypointId")
                                .HasName("pk_waypoint_locations");

                            b1.ToTable("waypoint_locations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WaypointId")
                                .HasConstraintName("fk_waypoint_locations_waypoints_waypoint_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_businesses_business_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_role_role_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Product", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_businesses_business_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Warehouse", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouses_businesses_business_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Entities.Batch", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_businesses_business_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batches_products_product_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Entities.InventoryItem", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_businesses_business_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_products_product_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_warehouses_warehouse_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Products.Domain.Model.Entities.StockMovement", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_businesses_business_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_products_product_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_warehouses_warehouse_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Sales.Domain.Model.Aggregates.Customer", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_businesses_business_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_businesses_business_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Sales.Domain.Model.Aggregates.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sales_customers_customer_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Sales.Domain.Model.Entities.SaleDetail", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_details_products_product_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Sales.Domain.Model.Aggregates.Sale", null)
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_details_sales_sale_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Aggregates.PurchaseOrder", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_businesses_business_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Aggregates.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_supplier_supplier_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Aggregates.Supplier", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Iam.Domain.Model.Aggregates.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_businesses_business_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Entities.PurchaseOrderDetail", b =>
                {
                    b.HasOne("Flowbit.Qullqa.Platform.Products.Domain.Model.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_details_products_product_id");

                    b.HasOne("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Aggregates.PurchaseOrder", null)
                        .WithMany("Details")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_details_purchase_orders_purchase_id");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Deliveries.Domain.Model.Aggregates.Delivery", b =>
                {
                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("Flowbit.Qullqa.Platform.Suppliers.Domain.Model.Aggregates.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
